# Config for Sarien and its variant, Arcada
[ids]
# AT keyboard is device 0001:0001
0001:0001

[main]
back = f1
refresh = f2
zoom = f3
scale = f4
camera = f5
scrolldown = f6
mute = f7
volumedown = f8
volumeup = f9
switchvideomode = f12

f1 = back 
f2 = refresh
f3 = zoom
f4 = scale
f5 = brightnessdown
f6 = brightnessup
f7 = mute
f8 = volumedown
f9 = volumeup
f12 = switchvideomode

leftmeta = capslock

[alt]
camera = kbdillumdown
scrolldown = kbdillumup
