# Config for Sarien and its variant, Arcada
[ids]
# AT keyboard is device 0001:0001
0001:0001

[main]
camera = brightnessdown
scrolldown = brightnessup

leftmeta = capslock

[alt]
camera = kbdillumdown
scrolldown = kbdillumup
